query PlayerSets($id: ID!, $page: Int, $perPage: Int, $after: Timestamp) {
	player(id: $id){
    sets(page: $page, perPage: $perPage, filters : {
      updatedAfter: $after
    }) {
      pageInfo {
        totalPages
      }
      nodes {
        fullRoundText
        completedAt
        id
        event {
          slug 
          name 
          tournament {
            name
          }
        }
        slots {
          entrant {
            participants {
              player {
                id
              }
            }
          }
        }
      }
    }
  }
}